"""Add audio

Revision ID: de7cd99a15da
Revises: 982cfe296588
Create Date: 2026-07-14 02:48:48.146521

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'de7cd99a15da'
down_revision: str | Sequence[str] | None = '982cfe296588'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
